/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoTPV;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edu
 */
public class Tpv extends javax.swing.JFrame {

    public class Liste implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            GregorianCalendar c = new GregorianCalendar();
            SimpleDateFormat f = new SimpleDateFormat("HH:mm:ss");
            lblHora.setText(f.format(c.getTime()));
            eliCobrar();
        }
    }

    public class timeMC implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {

            if (contMC < 1 && ultimoC != false) {
                tempMC.start();
                contMC++;
            } else if (contMC < 1 && ultimoP != false) {
                tempMC.start();
                contMC++;
            } else {
                ultimoC = false;
                ultimoP = false;
                cCero=false;
                contMC = 0;
                tempMC.stop();
                btnMC.setBackground(Color.LIGHT_GRAY);
                btnMP.setBackground(Color.LIGHT_GRAY);
                eliCobrar();
            }
            //System.out.println(contMC);
            //System.out.println(ultimoC);
            //System.out.println(ultimoP);
        }

    }

    /**
     * Creates new form Tpv
     */
    public Tpv() {
        initComponents();
        conexion = JDBC.conectarBD();
        hora = new javax.swing.Timer(1000, new Liste());
        hora.start();
        verCamareros();
        arrayModelos.add(new DefaultTableModel(new Object[][]{},
                new String[]{
                    "Cod", "Producto", "Cantidad", "Precio", "Total"
                }));
        jTable1.setModel(arrayModelos.get(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFondo = new javax.swing.JPanel();
        panAlimentos = new javax.swing.JPanel();
        btnRefrescos = new javax.swing.JButton();
        btnLicores = new javax.swing.JButton();
        btnPlatos = new javax.swing.JButton();
        btnTapas = new javax.swing.JButton();
        btnPostres = new javax.swing.JButton();
        btnCafes = new javax.swing.JButton();
        panSubAlimentos = new javax.swing.JPanel();
        panMenu = new javax.swing.JPanel();
        lblHora = new javax.swing.JLabel();
        btnOpciones = new javax.swing.JButton();
        btnOperaciones = new javax.swing.JButton();
        btnMain = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnComa = new javax.swing.JButton();
        btnEl = new javax.swing.JButton();
        btnMC = new javax.swing.JButton();
        btnMP = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        panLista = new javax.swing.JPanel();
        lblSTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPost = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        btnNCli = new javax.swing.JButton();
        cbxCamarero = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 791));
        setMinimumSize(new java.awt.Dimension(1280, 791));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 791));
        setResizable(false);
        getContentPane().setLayout(null);

        jPFondo.setBackground(new java.awt.Color(83, 77, 59));

        panAlimentos.setOpaque(false);

        btnRefrescos.setBackground(new java.awt.Color(36, 29, 29));
        btnRefrescos.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnRefrescos.setForeground(new java.awt.Color(204, 204, 204));
        btnRefrescos.setText("REFRESCOS");
        btnRefrescos.setContentAreaFilled(false);
        btnRefrescos.setOpaque(true);
        btnRefrescos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fondoNormal(evt);
            }
        });
        btnRefrescos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoAzul(evt);
            }
        });
        btnRefrescos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSub(evt);
            }
        });

        btnLicores.setBackground(new java.awt.Color(36, 29, 29));
        btnLicores.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnLicores.setForeground(new java.awt.Color(204, 204, 204));
        btnLicores.setText("LICORES");
        btnLicores.setContentAreaFilled(false);
        btnLicores.setOpaque(true);
        btnLicores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fondoNormal(evt);
            }
        });
        btnLicores.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoAzul(evt);
            }
        });
        btnLicores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSub(evt);
            }
        });

        btnPlatos.setBackground(new java.awt.Color(36, 29, 29));
        btnPlatos.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnPlatos.setForeground(new java.awt.Color(204, 204, 204));
        btnPlatos.setText("PLATOS");
        btnPlatos.setContentAreaFilled(false);
        btnPlatos.setOpaque(true);
        btnPlatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fondoNormal(evt);
            }
        });
        btnPlatos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoAzul(evt);
            }
        });
        btnPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSub(evt);
            }
        });

        btnTapas.setBackground(new java.awt.Color(36, 29, 29));
        btnTapas.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnTapas.setForeground(new java.awt.Color(204, 204, 204));
        btnTapas.setText("TAPAS");
        btnTapas.setContentAreaFilled(false);
        btnTapas.setOpaque(true);
        btnTapas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fondoNormal(evt);
            }
        });
        btnTapas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoAzul(evt);
            }
        });
        btnTapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSub(evt);
            }
        });

        btnPostres.setBackground(new java.awt.Color(36, 29, 29));
        btnPostres.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnPostres.setForeground(new java.awt.Color(204, 204, 204));
        btnPostres.setText("POSTRES");
        btnPostres.setContentAreaFilled(false);
        btnPostres.setOpaque(true);
        btnPostres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fondoNormal(evt);
            }
        });
        btnPostres.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoAzul(evt);
            }
        });
        btnPostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSub(evt);
            }
        });

        btnCafes.setBackground(new java.awt.Color(36, 29, 29));
        btnCafes.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnCafes.setForeground(new java.awt.Color(204, 204, 204));
        btnCafes.setText("CAFÉS");
        btnCafes.setContentAreaFilled(false);
        btnCafes.setOpaque(true);
        btnCafes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fondoNormal(evt);
            }
        });
        btnCafes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoAzul(evt);
            }
        });
        btnCafes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSub(evt);
            }
        });

        javax.swing.GroupLayout panAlimentosLayout = new javax.swing.GroupLayout(panAlimentos);
        panAlimentos.setLayout(panAlimentosLayout);
        panAlimentosLayout.setHorizontalGroup(
            panAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAlimentosLayout.createSequentialGroup()
                .addGroup(panAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAlimentosLayout.createSequentialGroup()
                        .addComponent(btnRefrescos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLicores, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTapas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panAlimentosLayout.createSequentialGroup()
                        .addComponent(btnPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPostres, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCafes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAlimentosLayout.setVerticalGroup(
            panAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAlimentosLayout.createSequentialGroup()
                .addGroup(panAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLicores, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTapas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPostres, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCafes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panSubAlimentos.setOpaque(false);

        javax.swing.GroupLayout panSubAlimentosLayout = new javax.swing.GroupLayout(panSubAlimentos);
        panSubAlimentos.setLayout(panSubAlimentosLayout);
        panSubAlimentosLayout.setHorizontalGroup(
            panSubAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panSubAlimentosLayout.setVerticalGroup(
            panSubAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panMenu.setBackground(new java.awt.Color(36, 29, 29));
        panMenu.setForeground(new java.awt.Color(32, 28, 28));

        lblHora.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHora.setForeground(new java.awt.Color(204, 204, 204));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnOpciones.setBackground(new java.awt.Color(36, 29, 29));
        btnOpciones.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnOpciones.setForeground(new java.awt.Color(204, 204, 204));
        btnOpciones.setText("Opciones");
        btnOpciones.setContentAreaFilled(false);
        btnOpciones.setOpaque(true);
        btnOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fondoNormal(evt);
            }
        });
        btnOpciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoAzul(evt);
            }
        });

        btnOperaciones.setBackground(new java.awt.Color(36, 29, 29));
        btnOperaciones.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnOperaciones.setForeground(new java.awt.Color(204, 204, 204));
        btnOperaciones.setText("Operaciones");
        btnOperaciones.setContentAreaFilled(false);
        btnOperaciones.setOpaque(true);
        btnOperaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fondoNormal(evt);
            }
        });
        btnOperaciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoAzul(evt);
            }
        });

        btnMain.setBackground(new java.awt.Color(74, 129, 205));
        btnMain.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnMain.setForeground(new java.awt.Color(204, 204, 204));
        btnMain.setContentAreaFilled(false);
        btnMain.setOpaque(true);

        btnPersonal.setBackground(new java.awt.Color(36, 29, 29));
        btnPersonal.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnPersonal.setForeground(new java.awt.Color(204, 204, 204));
        btnPersonal.setText("Personal");
        btnPersonal.setContentAreaFilled(false);
        btnPersonal.setOpaque(true);
        btnPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fondoNormal(evt);
            }
        });
        btnPersonal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoAzul(evt);
            }
        });

        javax.swing.GroupLayout panMenuLayout = new javax.swing.GroupLayout(panMenu);
        panMenu.setLayout(panMenuLayout);
        panMenuLayout.setHorizontalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMenuLayout.createSequentialGroup()
                .addComponent(btnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panMenuLayout.setVerticalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(btnOpciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addComponent(btnOperaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPersonal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn0.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn0.setText("0");
        btn0.setFocusPainted(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.setFocusPainted(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.setFocusPainted(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.setFocusPainted(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.setFocusPainted(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.setFocusPainted(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.setFocusPainted(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.setFocusPainted(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.setFocusPainted(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.setFocusPainted(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero(evt);
            }
        });

        btnComa.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnComa.setText(",");
        btnComa.setFocusPainted(false);
        btnComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero(evt);
            }
        });

        btnEl.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnEl.setForeground(new java.awt.Color(255, 0, 0));
        btnEl.setText("X");
        btnEl.setFocusPainted(false);
        btnEl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar(evt);
            }
        });

        btnMC.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnMC.setText("MC");
        btnMC.setFocusPainted(false);
        btnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCActionPerformed(evt);
            }
        });

        btnMP.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnMP.setText("MP");
        btnMP.setFocusPainted(false);
        btnMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPActionPerformed(evt);
            }
        });

        btnTicket.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnTicket.setText("Tck");
        btnTicket.setFocusPainted(false);
        btnTicket.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnTicket.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });

        btnCobrar.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        btnCobrar.setForeground(new java.awt.Color(0, 102, 0));
        btnCobrar.setText("Cobrar");
        btnCobrar.setFocusPainted(false);
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        panLista.setBackground(new java.awt.Color(95, 84, 50));
        panLista.setAlignmentX(0.0F);
        panLista.setAlignmentY(0.0F);
        panLista.setPreferredSize(new java.awt.Dimension(240, 351));

        lblSTotal.setBackground(new java.awt.Color(74, 129, 205));
        lblSTotal.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblSTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblSTotal.setText(" TOTAL");
        lblSTotal.setToolTipText("");
        lblSTotal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblSTotal.setOpaque(true);

        lblTotal.setBackground(new java.awt.Color(74, 129, 205));
        lblTotal.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0.0 €");
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblTotal.setOpaque(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod", "Producto", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(74, 129, 205));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout panListaLayout = new javax.swing.GroupLayout(panLista);
        panLista.setLayout(panListaLayout);
        panListaLayout.setHorizontalGroup(
            panListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2)
            .addGroup(panListaLayout.createSequentialGroup()
                .addComponent(lblSTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panListaLayout.setVerticalGroup(
            panListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPost.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnPost.setText(">");
        btnPost.setFocusPainted(false);
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAlante(evt);
            }
        });

        btnAnt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnAnt.setText("<");
        btnAnt.setFocusPainted(false);
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAtras(evt);
            }
        });

        btnNCli.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnNCli.setText("NUEVO CLIENTE");
        btnNCli.setFocusPainted(false);
        btnNCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adCli(evt);
            }
        });

        cbxCamarero.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panSubAlimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panAlimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFondoLayout.createSequentialGroup()
                        .addComponent(cbxCamarero, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNCli, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPost, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                        .addGroup(jPFondoLayout.createSequentialGroup()
                            .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPFondoLayout.createSequentialGroup()
                                    .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnComa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPFondoLayout.createSequentialGroup()
                                    .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnMP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPFondoLayout.createSequentialGroup()
                        .addComponent(panAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panSubAlimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPFondoLayout.createSequentialGroup()
                        .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxCamarero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPFondoLayout.createSequentialGroup()
                                .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnComa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPFondo);
        jPFondo.setBounds(0, 0, 1280, 791);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verCamareros() {
        st = JDBC.crearSentencia(conexion);
        rs = JDBC.crearResultado(st, "SELECT nombre_c FROM Camarero;");
        try {
            while (rs.next()) {
                cbxCamarero.addItem(rs.getString("nombre_c"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tpv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fondoAzul(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoAzul
        JButton boton = (JButton) evt.getSource();
        boton.setBackground(new java.awt.Color(74, 129, 205));
    }//GEN-LAST:event_fondoAzul

    private void fondoNormal(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoNormal
        JButton boton = (JButton) evt.getSource();
        boton.setBackground(new java.awt.Color(36, 29, 29));
    }//GEN-LAST:event_fondoNormal

    private void mSub(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSub

        panSubAlimentos.removeAll();
        panSubAlimentos.setVisible(false);
        panSubAlimentos.setVisible(true);

        JButton boton = (JButton) evt.getSource();
        String tipo;
        switch (boton.getText().toLowerCase()) {
            case "refrescos":
                tipo = "refrescos";
                break;
            case "licores":
                tipo = "licores";
                break;
            case "tapas":
                tipo = "tapas";
                break;
            case "platos":
                tipo = "platos";
                break;
            case "postres":
                tipo = "postres";
                break;
            case "cafés":
                tipo = "cafes";
                break;
            default:
                tipo = "";
                break;
        }
        st = JDBC.crearSentencia(conexion);

        //COUNT PARA CREAR LOS BOTONES
        String c = "SELECT COUNT (*) AS count FROM Producto WHERE tipo = '" + tipo + "';";
        rs = JDBC.crearResultado(st, c);

        try {
            if (rs.next()) {
                count = rs.getInt("count");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tpv.class.getName()).log(Level.SEVERE, null, ex);
        }

        btnSMnu = new javax.swing.JButton[count];
        aProd = new Productos[count];
        int dBotones = 0;
        String q = "SELECT * FROM Producto WHERE tipo = '" + tipo + "';";
        rs = JDBC.crearResultado(st, q);
        int h = 0;
        int hB = 0;
        try {
            while (rs.next()) {
                //añade fila
                if (hB == 6) {
                    h += 120 + 8;
                    hB = 0;
                }
                btnSMnu[dBotones] = new javax.swing.JButton();
                panSubAlimentos.add(btnSMnu[dBotones]);
                btnSMnu[dBotones].setBounds(120 * hB + 8 * hB, h, 120, 120);
                btnSMnu[dBotones].setText(rs.getString("nombre"));
                btnSMnu[dBotones].setBackground(new java.awt.Color(36, 29, 29));
                btnSMnu[dBotones].setContentAreaFilled(false);
                btnSMnu[dBotones].setOpaque(true);

                //construimos los objetos productos
                aProd[dBotones] = new Productos(rs.getInt("codigo"), btnSMnu[dBotones].getText(), rs.getString("tipo"), rs.getInt("cantidad"), rs.getDouble("precio"));
                //EVENTO
                btnSMnu[dBotones].addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        evtBoton(evt);
                    }
                });

                //System.out.println(hB + "" + dBotones);
                hB++;
                dBotones++;
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(Tpv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mSub

    private void evtBoton(java.awt.event.ActionEvent evt) {

        m = (DefaultTableModel) jTable1.getModel();

        addM1P = true;
        javax.swing.JButton botonPulsado = (javax.swing.JButton) evt.getSource();
        for (int i = 0; i < count; i++) {
            if (botonPulsado.equals(btnSMnu[i])) {
                //coger nombre en el modelo
                for (int n = 0; n < m.getRowCount(); n++) {
                    String nombre = m.getValueAt(n, 1).toString();
                    cant = (Integer) Integer.parseInt(m.getValueAt(n, 2).toString());

                    //System.out.println(cant);
                    if (aProd[i].getNombre().equals(nombre)) {
                        cant += 1;
                        m.setValueAt(cant, n, 2);
                        m.setValueAt((Double) Double.parseDouble(m.getValueAt(n, 3).toString()) * cant, n, 4);
                        addM1P = false;
                        verTotal();

                    }
                }
                if (addM1P) {
                    m.addRow(new Object[]{
                        aProd[i].getCod(), aProd[i].getNombre(), cantidad, (aProd[i].getPrecio()), aProd[i].getPrecio() * cantidad}
                    );
                }
            }
        }
        verTotal();
    }

    private void verTotal() {
        double total = 0;
        double subtotal = 0;
        
        for (int i = 0; i < m.getRowCount(); i++) {
            subtotal = Double.parseDouble(m.getValueAt(i, 4).toString());
            total = total + subtotal;
        }
        lblTotal.setText(total + " €");
        if(total == 0){
             lblTotal.setText("0.0 €");
        }
    }


    private void adCli(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adCli
        int ultPos = arrayModelos.size();
        arrayModelos.add(new DefaultTableModel(new Object[][]{},
                new String[]{
                    "Cod", "Producto", "Cantidad", "Precio", "Total"
                }));

        jTable1.setModel(arrayModelos.get(ultPos));
        lblTotal.setText("0.0 €");
        //System.out.println(arrayModelos.size()+""+ultPos);
    }//GEN-LAST:event_adCli

    private void mAtras(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAtras
        int am = arrayModelos.size();
        for (int i = 0; i < am; i++) {
            try {
                if (jTable1.getModel().equals(arrayModelos.get(i))) {
                    jTable1.setModel(arrayModelos.get(i - 1));

                    m = (DefaultTableModel) jTable1.getModel();
                    verTotal();
                }
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_mAtras

    private void mAlante(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAlante
        int am = arrayModelos.size();
        for (int i = 0; i < am; i++) {
            try {
                if (jTable1.getModel().equals(arrayModelos.get(i))) {
                    jTable1.setModel(arrayModelos.get(i + 1));

                    m = (DefaultTableModel) jTable1.getModel();
                    verTotal();
                }
            } catch (Exception e) {
            }
        }
     }//GEN-LAST:event_mAlante

    private void btnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCActionPerformed
        if (ultimoC == false && ultimoP == false) {
            btnMC.setBackground(Color.green);
            ultimoC = true;
            tempoMC();
            valor = "";
        }
    }//GEN-LAST:event_btnMCActionPerformed

    private void tempoMC() {
        tempMC = new javax.swing.Timer(1000, new timeMC());
        tempMC.start();
    }

    private void numero(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero
        JButton boton = (JButton) evt.getSource();

        if(jTable1.getSelectedRow()!=-1){
        if (ultimoC) {
            
            if(boton.getText().equals("0") && cCero==false){
        valor = "";
            }else{
        valor = valor + boton.getText();
        
                cCero=true;
            }
            contMC=0;
            try {
                double total = (Double) Double.parseDouble(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3).toString()) * ((Double) Double.parseDouble(valor));
                total = (Math.round(total*100));
                total = total / 100;
                jTable1.getModel().setValueAt(valor, jTable1.getSelectedRow(), 2);
                jTable1.getModel().setValueAt(total, jTable1.getSelectedRow(), 4);
                
                m = (DefaultTableModel) jTable1.getModel();
                verTotal();

            } catch (Exception ex) {
            }
        } 
        
        else if (ultimoP) {
            
            if(boton.getText().equals(",")){
               String valor1 = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3).toString();
                if(valor1.contains(".")==false && !valor1.equals("")){
                    valor = valor + ".";
                }
            }else if(boton.getText().equals("0") && valor.equals("0")){
        valor = "0";
            }else{
            
        valor = valor + boton.getText();
            contMC=0;

                double total = (Double)Double.parseDouble(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2).toString()) * ((Double) Double.parseDouble(valor));
                total = (Math.round(total*100));
                total = total / 100;
                jTable1.getModel().setValueAt(valor, jTable1.getSelectedRow(), 3);
                jTable1.getModel().setValueAt(total, jTable1.getSelectedRow(), 4);

                m = (DefaultTableModel) jTable1.getModel();
                verTotal();

           
            }
        }}
    }//GEN-LAST:event_numero

    private void btnMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPActionPerformed
        if (ultimoP == false) {
            btnMP.setBackground(Color.green);
            ultimoP = true;
            tempoMC();
            valor = "";
        }
    }//GEN-LAST:event_btnMPActionPerformed

    private void eliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar
        try{((DefaultTableModel)jTable1.getModel()).removeRow(jTable1.getSelectedRow());
         m = (DefaultTableModel) jTable1.getModel();
         verTotal();
        }catch (Exception ex){}
    }//GEN-LAST:event_eliminar

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        javax.swing.table.DefaultTableModel m = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        double totales=0.00;
        System.out.println("===============================================");
        System.out.println("                Le ha atendido   ");
        System.out.println("                "+cbxCamarero.getModel().getSelectedItem().toString());
        System.out.println("=============================================== \n\n");
        
        
        System.out.printf("%-20s %4s %9s %10s" ,"Producto","U ","P/U ","   TOTAL   \n");
        System.out.printf("%-20S %4s %9s %10s" ,"===================","===","========","  ========\n");
        for(int f =0; f<m.getRowCount(); f++){
            for(int c = 1; c<m.getColumnCount(); c ++){
                if(c==1){
                System.out.printf("%-20s", m.getValueAt(f, c));
                }else if(c==2){
                System.out.printf("%4s", m.getValueAt(f, c).toString());
                }else if(c==3){
                   double d = Double.parseDouble(m.getValueAt(f, c).toString());
                    System.out.printf("%10.2f", d);
                }else{
                     System.out.printf("%10.2f", m.getValueAt(f, c));
                     totales +=  Double.parseDouble(m.getValueAt(f, c).toString());
                }
            }
            System.out.println("\n");            
        }
        System.out.println("                              ----------------");
        System.out.printf("%-20s %2s %9s %10.2f € " ,"","","TOTAL", totales);
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        DefaultTableModel mActu =(DefaultTableModel)jTable1.getModel();
        try{
        for(DefaultTableModel m : arrayModelos){
            if(m.equals(mActu)){
                 if(lblTotal.getText().equals("0.0 €")){
                    arrayModelos.remove(m);
                }else{
                ///TOCHACO PA VOLVERSE LOCO
                
                     
                
                
                
                
                
                ///FIN DE TOCHACO
                
                arrayModelos.remove(m);
            }
        }}
        }catch(Exception ex){
        }
        
        try{
        jTable1.setModel(arrayModelos.get(0));
        
        m = (DefaultTableModel) jTable1.getModel();
        verTotal();
        
        }catch(Exception ex){
            try {
            borrarFilas();
            verTotal();
            }catch(Exception exx){}
            
        }
    }//GEN-LAST:event_btnCobrarActionPerformed

    public void borrarFilas(){
        DefaultTableModel m = (DefaultTableModel)jTable1.getModel();
        while(m.getRowCount()!=0){
            m.removeRow(0);
        }
    }
    
    public void eliCobrar (){
        if(lblTotal.getText().equals("0.0 €")){
            btnCobrar.setForeground(Color.red);
            btnCobrar.setText("Eliminar");
        }else{
            btnCobrar.setForeground(new java.awt.Color(0, 102, 0));
            btnCobrar.setText("Cobrar");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tpv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tpv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tpv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tpv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tpv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnCafes;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnComa;
    private javax.swing.JButton btnEl;
    private javax.swing.JButton btnLicores;
    private javax.swing.JButton btnMC;
    private javax.swing.JButton btnMP;
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnNCli;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnOperaciones;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnPlatos;
    private javax.swing.JButton btnPost;
    private javax.swing.JButton btnPostres;
    private javax.swing.JButton btnRefrescos;
    private javax.swing.JButton btnTapas;
    private javax.swing.JButton btnTicket;
    private javax.swing.JComboBox cbxCamarero;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblSTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panAlimentos;
    private javax.swing.JPanel panLista;
    private javax.swing.JPanel panMenu;
    private javax.swing.JPanel panSubAlimentos;
    // End of variables declaration//GEN-END:variables
    java.sql.Statement st;
    java.sql.ResultSet rs;
    java.sql.Connection conexion;
    public int count = 0;
    javax.swing.JButton[] btnSMnu;
    public Productos[] aProd;
    javax.swing.Timer hora;
    DefaultTableModel m;
    ArrayList<javax.swing.table.DefaultTableModel> arrayModelos = new ArrayList();
    int cantidad = 1;
    boolean ultimoC;
    boolean ultimoP;
    boolean addM1P = true;
    int cant;
    String valor = "";
    boolean cCero= false;
   

    javax.swing.Timer tempMC;
    int contMC;
}
